[build]
publish = "public"
command = "./stackbit-build.sh"

[[redirects]]
    from = "https://drewb.tech/*"
    to = "https://developerspin.com/:splat"
    force = true

    from = "https://developerspin.com/posts/*"
    to = "https://developerspin.com/:splat"
    force = true
